coverage:
  status:
    project:
      default:
        target: 0%
        paths:
        - autoload
    patch:
      default:
        target: 0%
        paths:
        - autoload

comment:
  layout: "reach, diff, flags, files"
  branches:
    - master
  behavior: default

