" Transform to lcov(1) format
" Spec: geninfo(1) / FILES
" Ref: http://ltp.sourceforge.net/coverage/lcov/geninfo.1.php
"
" Author: Luma
" License: Unlicense

" type ProfileJSON is generated by ProfileParser.parse()

" @param {ProfileJSON} profile
function! s:profile_to_lcov(profile) abort

  return res
endfunction
